export const ADD_GENRE = "ADD_GENRE";
export const ADD_SUBGENRE = "ADD_SUBGENRE";
export const ADD_NEW_GENRE = "ADD_NEW_GENRE";
export const ADD_NEW_GENRE_TITLE = "ADD_NEW_GENRE_TITLE";
export const ADD_NEW_GENRE_DESCRIPTION = "ADD_NEW_GENRE_DESCRIPTION";